#roast
ROAS = [
    "UDAH GAK GUNA"
    "DI TAMBAH HINA"
    "MERANA PULA, LENGKAP KALI KEHIDUPAN KAU MACAM SINETRON DI INDOSIAR YANG SERING DI GUNA GUNA."
]
    

#sukasuka
SUKASUKA = [
    "MINIMAL NIH YA LU MANDI DULU"
    "TERUS LU MINTA BEDAKIN SAMA EMAK LU"
    "ABIS ITU BARU DAH LU NGAKU NGAKU KALO LU TUH PANJAHAT KELAMIN"
]


ram_a = "YAELAHH DONGOO KALI KAU DEKKUH"
ram_b = "BABU ALIANSI BANYAK KALII GAYANYA,UDAH GAK KERAS MASIH AJA BANYAK BACOTT"
ram_c = "CANTIKK SII TAPI SAYANGNYA BABU ALIANSI"
ram_d = "LAGI NYARI KOSAKATA YA DEKKUH DI GC LAINN, BHAKSSS"
ram_e = "EH BABU,KALO DI BILANGIN AMA YANG LEBIH TUA TUH JANGAN BATU NGENTOT,OTAK LU TUH LEMAH GOBLOK, DI KASIH TAU MALAH BATU NGENTOT KOSAKATA MASIH CARI DI GC LAEN BLAGUNYA BUKAN MAEN DEKKUHH 
ram_f = "MENDING LU BUKA YOUTUBE CARI TUTORIAL KIYOMASA, DARI PADA TYPINGAN SAMPAH KAYA LU TOLOL, GAK BIKIN GEMETER"
ram_g = "GAK JELASS KONTOL MASIH KECIL,BIJINYA SEUKURAN KERIKIL"
ram_h = "HABIS COLI YA DEKKUH, PANTESSSS NAMBAH DONGO !"
ram_i = "ITU KAN KOSAKATANYA NGAMBIL !"
ram_j = "JANGAN KERAS-KERAS DEK, KERASNYA LU TUH CUMA DI DEPAN CEWE DOANG JADI JATOHNYA CAPER NGENTOT !"
ram_k = "KALO CUMA LU DOANG MAH IBARAT KATA KAYA GW LAWAN ANAK TK !"
ram_l = "Wa'alaikumsalam, ada apa?"
ram_m = "MUKA LU NGAMBIL DI PINTEREST KAN??GAK BERANI PAKE MUKA HINA LU YA TOLOL"
ram_n = "NIH DIA YANG GW TUNGGUIN DARI KEMAREN, DATENG JUGA SI BABU WUAHAHAHA"
ram_o = "ORANG MAH KALO GAK GUNA MINIMAL MAH MIKIRR DEKKUH, UDAH GAK GUNA BEBAN PULA MENDING MAEN POU AJA BERSIHIN TAI YANG KAYA MUKA LU, BHAKSS"
ram_p = "Assalamu'alaikum"
ram_q = "QUNYUKKKK BANYAK KALI LAGANYA, TAPI JATOHHNYA CAPER SIHH, CUIHH!"
ram_r = "RASANYA KOK KAYA GAK ADA APA APA YA, PADAHAL LU MAH UDAH BACOT PANJANG KALI LEBAR TAPI BELOM KERASA HADEHH"
ram_s = "SAYANG-SAYANG MENTAL LU NANTI DOWN KALO LAWAN GUA, BHAKSSS"
ram_t = "TERIMA KASIH KEK MINIMAL NGENTOT,UDAH GW KASIH TEMPAT LU UNTUK CAPER SANA SINI TOD"
ram_u = "UDAH HINA,BANYAK GAYA NGENTOT MASIH MENDING GW LADENIN"
ram_v = "NORAK ANJING MAENIN BOT TERUS KONTOL, NANTI DELLAY YANG DI SALAHIN BOT NYA MEMEK"
ram_w = "WAR-WAR TAI ANJING BABI,CUMA DATENG MODAL MENTAL TEMPE AJA BELAGU"
ram_x = "HAPENYA KENTANG,SOK MENANTANG"
ram_y = "MUKA LU TUH UDAH HINA, JADI JANGAN DIBUAT NAMBAH HINA NANTI HIDUP LU JADI GAK GUNA TOLOLL"
ram_z = "BANYAK GAYA TAPI BUKAN ORANG KAYA,BAPAK LU MASIH PAKE BAJU PARTAI DAPET DARI SOGOKAN NYOBLOS AJA UDAH GEDE LAGANYA"


